version: "3.8"

services:
  database:
    container_name: postgres-container
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: penguin_dev
      POSTGRES_USER: postgres
      POSTGRES_DB: shop
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: 
      - microservices
  node_exporter:
    container_name: node_exporter_container
    restart: always
    image: prom/node-exporter
    ports:
     - '9101:9100'
    networks:
      - microservices

  grafana:
    container_name: grafana_container
    restart: always
    image: grafana/grafana
    ports:
      - '3005:3000'
    networks: 
      - microservices

  jeager:
    container_name: jeager_container
    restart: always
    image: jaegertracing/all-in-one:1.56
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "16686:16686"
      - "4318:4318"
      - "9411:9411"
    networks:
      - microservices
volumes:
  db:

networks:
  microservices:
    name: microservices