global:
  scrape_interval: 10s # every 10 seconds, call to jobs and get data once
  scrape_timeout: 10s # after 10 seconds, if can't get data from exporter to timeout

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['localhost:9090']
    
- job_name: node_exporter
  static_configs:
  - targets: ['host.docker.internal:9101']