// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Item struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Quantity    int64
	Price       float64
	OrderID     uuid.UUID
}

type Order struct {
	ID              uuid.UUID
	AccountEmail    string
	DeliveryAddress string
	CancelReason    string
	TotalPrice      float64
	Paid            sql.NullBool
	Submitted       sql.NullBool
	Completed       sql.NullBool
	Canceled        sql.NullBool
}

type Payment struct {
	PaymentID     uuid.UUID
	PaymentedTime time.Time
	OrderID       uuid.UUID
}
