// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order.proto

package orderservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountEmail    string                 `protobuf:"bytes,1,opt,name=account_email,json=accountEmail,proto3" json:"account_email,omitempty"`
	ShopItems       []*ShopItem            `protobuf:"bytes,2,rep,name=shop_items,json=shopItems,proto3" json:"shop_items,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetAccountEmail() string {
	if x != nil {
		return x.AccountEmail
	}
	return ""
}

func (x *CreateOrderRequest) GetShopItems() []*ShopItem {
	if x != nil {
		return x.ShopItems
	}
	return nil
}

func (x *CreateOrderRequest) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

type PayOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	Payment       *Payment               `protobuf:"bytes,2,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *PayOrderRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *PayOrderRequest) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type PayOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderResponse) Reset() {
	*x = PayOrderResponse{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResponse) ProtoMessage() {}

func (x *PayOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResponse.ProtoReflect.Descriptor instead.
func (*PayOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *PayOrderResponse) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitOrderRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitOrderResponse) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

type GetOrderByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRequest) Reset() {
	*x = GetOrderByIDRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRequest) ProtoMessage() {}

func (x *GetOrderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderByIDRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

type GetOrderByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDResponse) Reset() {
	*x = GetOrderByIDResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDResponse) ProtoMessage() {}

func (x *GetOrderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrderByIDResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderByIDResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateShoppingCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	ShopItems     []*ShopItem            `protobuf:"bytes,2,rep,name=shop_items,json=shopItems,proto3" json:"shop_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShoppingCartRequest) Reset() {
	*x = UpdateShoppingCartRequest{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShoppingCartRequest) ProtoMessage() {}

func (x *UpdateShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*UpdateShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateShoppingCartRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *UpdateShoppingCartRequest) GetShopItems() []*ShopItem {
	if x != nil {
		return x.ShopItems
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateId   string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	CancelReason  string                 `protobuf:"bytes,2,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *CancelOrderRequest) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type CompleteOrderRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AggregateId       string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	DeliveryTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=delivery_timestamp,json=deliveryTimestamp,proto3" json:"delivery_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompleteOrderRequest) Reset() {
	*x = CompleteOrderRequest{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderRequest) ProtoMessage() {}

func (x *CompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*CompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteOrderRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *CompleteOrderRequest) GetDeliveryTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTimestamp
	}
	return nil
}

type ChangeDeliveryAddressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AggregateId     string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,2,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeDeliveryAddressRequest) Reset() {
	*x = ChangeDeliveryAddressRequest{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDeliveryAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDeliveryAddressRequest) ProtoMessage() {}

func (x *ChangeDeliveryAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDeliveryAddressRequest.ProtoReflect.Descriptor instead.
func (*ChangeDeliveryAddressRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeDeliveryAddressRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *ChangeDeliveryAddressRequest) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchText    string                 `protobuf:"bytes,1,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRequest) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *SearchRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *SearchResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShopItems         []*ShopItem            `protobuf:"bytes,2,rep,name=shop_items,json=shopItems,proto3" json:"shop_items,omitempty"`
	Paid              bool                   `protobuf:"varint,3,opt,name=paid,proto3" json:"paid,omitempty"`
	Submitted         bool                   `protobuf:"varint,4,opt,name=submitted,proto3" json:"submitted,omitempty"`
	Completed         bool                   `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	Canceled          bool                   `protobuf:"varint,6,opt,name=canceled,proto3" json:"canceled,omitempty"`
	TotalPrice        float64                `protobuf:"fixed64,7,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	AccountEmail      string                 `protobuf:"bytes,8,opt,name=account_email,json=accountEmail,proto3" json:"account_email,omitempty"`
	CancelReason      string                 `protobuf:"bytes,9,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	DeliveryAddress   string                 `protobuf:"bytes,10,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	DeliveryTimestamp *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=delivery_timestamp,json=deliveryTimestamp,proto3" json:"delivery_timestamp,omitempty"`
	Payment           *Payment               `protobuf:"bytes,12,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetShopItems() []*ShopItem {
	if x != nil {
		return x.ShopItems
	}
	return nil
}

func (x *Order) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *Order) GetSubmitted() bool {
	if x != nil {
		return x.Submitted
	}
	return false
}

func (x *Order) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Order) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetAccountEmail() string {
	if x != nil {
		return x.AccountEmail
	}
	return ""
}

func (x *Order) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *Order) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *Order) GetDeliveryTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTimestamp
	}
	return nil
}

func (x *Order) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalPages    int64                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Pagination) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desription    string                 `protobuf:"bytes,3,opt,name=desription,proto3" json:"desription,omitempty"`
	Quantity      uint64                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *ShopItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShopItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShopItem) GetDesription() string {
	if x != nil {
		return x.Desription
	}
	return ""
}

func (x *ShopItem) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShopItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\forderservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9b\x01\n" +
	"\x12CreateOrderRequest\x12#\n" +
	"\raccount_email\x18\x01 \x01(\tR\faccountEmail\x125\n" +
	"\n" +
	"shop_items\x18\x02 \x03(\v2\x16.orderservice.ShopItemR\tshopItems\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\"8\n" +
	"\x13CreateOrderResponse\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\"e\n" +
	"\x0fPayOrderRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12/\n" +
	"\apayment\x18\x02 \x01(\v2\x15.orderservice.PaymentR\apayment\"5\n" +
	"\x10PayOrderResponse\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\"7\n" +
	"\x12SubmitOrderRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\"8\n" +
	"\x13SubmitOrderResponse\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\"8\n" +
	"\x13GetOrderByIDRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\"A\n" +
	"\x14GetOrderByIDResponse\x12)\n" +
	"\x05order\x18\x01 \x01(\v2\x13.orderservice.OrderR\x05order\"u\n" +
	"\x19UpdateShoppingCartRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x125\n" +
	"\n" +
	"shop_items\x18\x02 \x03(\v2\x16.orderservice.ShopItemR\tshopItems\"\\\n" +
	"\x12CancelOrderRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12#\n" +
	"\rcancel_reason\x18\x02 \x01(\tR\fcancelReason\"\x84\x01\n" +
	"\x14CompleteOrderRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12I\n" +
	"\x12delivery_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x11deliveryTimestamp\"l\n" +
	"\x1cChangeDeliveryAddressRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12)\n" +
	"\x10delivery_address\x18\x02 \x01(\tR\x0fdeliveryAddress\"X\n" +
	"\rSearchRequest\x12\x1f\n" +
	"\vsearch_text\x18\x01 \x01(\tR\n" +
	"searchText\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"w\n" +
	"\x0eSearchResponse\x128\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x18.orderservice.PaginationR\n" +
	"pagination\x12+\n" +
	"\x06orders\x18\x02 \x03(\v2\x13.orderservice.OrderR\x06orders\"\xcc\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\n" +
	"shop_items\x18\x02 \x03(\v2\x16.orderservice.ShopItemR\tshopItems\x12\x12\n" +
	"\x04paid\x18\x03 \x01(\bR\x04paid\x12\x1c\n" +
	"\tsubmitted\x18\x04 \x01(\bR\tsubmitted\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\bR\tcompleted\x12\x1a\n" +
	"\bcanceled\x18\x06 \x01(\bR\bcanceled\x12\x1f\n" +
	"\vtotal_price\x18\a \x01(\x01R\n" +
	"totalPrice\x12#\n" +
	"\raccount_email\x18\b \x01(\tR\faccountEmail\x12#\n" +
	"\rcancel_reason\x18\t \x01(\tR\fcancelReason\x12)\n" +
	"\x10delivery_address\x18\n" +
	" \x01(\tR\x0fdeliveryAddress\x12I\n" +
	"\x12delivery_timestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x11deliveryTimestamp\x12/\n" +
	"\apayment\x18\f \x01(\v2\x15.orderservice.PaymentR\apayment\"\x91\x01\n" +
	"\n" +
	"Pagination\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x03R\n" +
	"totalPages\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"S\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x01\n" +
	"\bShopItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"desription\x18\x03 \x01(\tR\n" +
	"desription\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x04R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price2\xf2\x05\n" +
	"\fOrderService\x12R\n" +
	"\vCreateOrder\x12 .orderservice.CreateOrderRequest\x1a!.orderservice.CreateOrderResponse\x12I\n" +
	"\bPayOrder\x12\x1d.orderservice.PayOrderRequest\x1a\x1e.orderservice.PayOrderResponse\x12R\n" +
	"\vSumbitOrder\x12 .orderservice.SubmitOrderRequest\x1a!.orderservice.SubmitOrderResponse\x12U\n" +
	"\x12UpdateShoppingCart\x12'.orderservice.UpdateShoppingCartRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\vCancelOrder\x12 .orderservice.CancelOrderRequest\x1a!.orderservice.CreateOrderResponse\x12K\n" +
	"\rCompleteOrder\x12\".orderservice.CompleteOrderRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x15ChangeDeliveryAddress\x12*.orderservice.ChangeDeliveryAddressRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\fGetOrderByID\x12!.orderservice.GetOrderByIDRequest\x1a\".orderservice.GetOrderByIDResponse\x12C\n" +
	"\x06Search\x12\x1b.orderservice.SearchRequest\x1a\x1c.orderservice.SearchResponseB\x11Z\x0f./;orderserviceb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),           // 0: orderservice.CreateOrderRequest
	(*CreateOrderResponse)(nil),          // 1: orderservice.CreateOrderResponse
	(*PayOrderRequest)(nil),              // 2: orderservice.PayOrderRequest
	(*PayOrderResponse)(nil),             // 3: orderservice.PayOrderResponse
	(*SubmitOrderRequest)(nil),           // 4: orderservice.SubmitOrderRequest
	(*SubmitOrderResponse)(nil),          // 5: orderservice.SubmitOrderResponse
	(*GetOrderByIDRequest)(nil),          // 6: orderservice.GetOrderByIDRequest
	(*GetOrderByIDResponse)(nil),         // 7: orderservice.GetOrderByIDResponse
	(*UpdateShoppingCartRequest)(nil),    // 8: orderservice.UpdateShoppingCartRequest
	(*CancelOrderRequest)(nil),           // 9: orderservice.CancelOrderRequest
	(*CompleteOrderRequest)(nil),         // 10: orderservice.CompleteOrderRequest
	(*ChangeDeliveryAddressRequest)(nil), // 11: orderservice.ChangeDeliveryAddressRequest
	(*SearchRequest)(nil),                // 12: orderservice.SearchRequest
	(*SearchResponse)(nil),               // 13: orderservice.SearchResponse
	(*Order)(nil),                        // 14: orderservice.Order
	(*Pagination)(nil),                   // 15: orderservice.Pagination
	(*Payment)(nil),                      // 16: orderservice.Payment
	(*ShopItem)(nil),                     // 17: orderservice.ShopItem
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 19: google.protobuf.Empty
}
var file_order_proto_depIdxs = []int32{
	17, // 0: orderservice.CreateOrderRequest.shop_items:type_name -> orderservice.ShopItem
	16, // 1: orderservice.PayOrderRequest.payment:type_name -> orderservice.Payment
	14, // 2: orderservice.GetOrderByIDResponse.order:type_name -> orderservice.Order
	17, // 3: orderservice.UpdateShoppingCartRequest.shop_items:type_name -> orderservice.ShopItem
	18, // 4: orderservice.CompleteOrderRequest.delivery_timestamp:type_name -> google.protobuf.Timestamp
	15, // 5: orderservice.SearchResponse.pagination:type_name -> orderservice.Pagination
	14, // 6: orderservice.SearchResponse.orders:type_name -> orderservice.Order
	17, // 7: orderservice.Order.shop_items:type_name -> orderservice.ShopItem
	18, // 8: orderservice.Order.delivery_timestamp:type_name -> google.protobuf.Timestamp
	16, // 9: orderservice.Order.payment:type_name -> orderservice.Payment
	18, // 10: orderservice.Payment.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 11: orderservice.OrderService.CreateOrder:input_type -> orderservice.CreateOrderRequest
	2,  // 12: orderservice.OrderService.PayOrder:input_type -> orderservice.PayOrderRequest
	4,  // 13: orderservice.OrderService.SumbitOrder:input_type -> orderservice.SubmitOrderRequest
	8,  // 14: orderservice.OrderService.UpdateShoppingCart:input_type -> orderservice.UpdateShoppingCartRequest
	9,  // 15: orderservice.OrderService.CancelOrder:input_type -> orderservice.CancelOrderRequest
	10, // 16: orderservice.OrderService.CompleteOrder:input_type -> orderservice.CompleteOrderRequest
	11, // 17: orderservice.OrderService.ChangeDeliveryAddress:input_type -> orderservice.ChangeDeliveryAddressRequest
	6,  // 18: orderservice.OrderService.GetOrderByID:input_type -> orderservice.GetOrderByIDRequest
	12, // 19: orderservice.OrderService.Search:input_type -> orderservice.SearchRequest
	1,  // 20: orderservice.OrderService.CreateOrder:output_type -> orderservice.CreateOrderResponse
	3,  // 21: orderservice.OrderService.PayOrder:output_type -> orderservice.PayOrderResponse
	5,  // 22: orderservice.OrderService.SumbitOrder:output_type -> orderservice.SubmitOrderResponse
	19, // 23: orderservice.OrderService.UpdateShoppingCart:output_type -> google.protobuf.Empty
	1,  // 24: orderservice.OrderService.CancelOrder:output_type -> orderservice.CreateOrderResponse
	19, // 25: orderservice.OrderService.CompleteOrder:output_type -> google.protobuf.Empty
	19, // 26: orderservice.OrderService.ChangeDeliveryAddress:output_type -> google.protobuf.Empty
	7,  // 27: orderservice.OrderService.GetOrderByID:output_type -> orderservice.GetOrderByIDResponse
	13, // 28: orderservice.OrderService.Search:output_type -> orderservice.SearchResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
